name: agent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  flutter_screenutil: ^5.6.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  flutter_svg: ^1.1.6
  bloc_concurrency: ^0.2.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.2
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.6
  awesome_calendar: ^1.1.3
  bot_toast: ^4.0.3
  flutter_gen: ^5.0.3
  percent_indicator: ^4.2.2
  super_rich_text: ^1.0.0
  device_info_plus: ^8.0.0
  mask_text_input_formatter: ^2.4.0
  uikit:
    git:
      url: https://gitlab.com/tlps-project/ui-kit.git
  animated_digit: ^3.2.1
  yandex_mapkit: ^3.2.0
  google_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.2
  build_runner: ^2.3.2
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/color/
    - assets/images/
    - assets/images/icons/
    - assets/langs/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf

flutter_gen:
  output: lib/core/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml